name: nearbymenus
description: Nearby Menus White Label.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Last iOS version
# version: 1.0.15
# Last Android version
version: 1.0.0+25
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.3 
  draggable_scrollbar: ^0.1.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutter_datetime_picker: ^1.5.1
  flutter_image_compress: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^14.0.0-dev.2
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.0.8
  image_picker: ^0.8.4
  intl: ^0.18.0
  location: ^4.3.0
  permission_handler: ^10.0.0
  provider: ^6.0.0
  purchases_flutter: ^4.11.1
  rate_my_app: ^1.1.1
  responsive_framework: ^0.2.0
  rxdart: ^0.27.2
  macos_ui: ^1.4.1

#dependency_overrides:
#  firebase_core: 0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/LauncherIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/LauncherIcon.png
    - assets/OriginalonTransparent.png
    - assets/chequered-flag.png
    - assets/chequered-flagiOS.png
    - assets/bigHome.png
    - assets/bigHomeiOS.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
