// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwVeGaERZIOmveD8HpN4ODly0ZRy6eI8',
    appId: '1:216593913852:web:fe11c6bb38246b692f8479',
    messagingSenderId: '216593913852',
    projectId: 'nearby-menus-be6e3',
    authDomain: 'nearby-menus-be6e3.firebaseapp.com',
    databaseURL: 'https://nearby-menus-be6e3.firebaseio.com',
    storageBucket: 'nearby-menus-be6e3.appspot.com',
    measurementId: 'G-08HVMQ8H90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQgRbrjZs_RyGSE0w-Kaoc68HZqvre1c8',
    appId: '1:216593913852:android:0b178486293532152f8479',
    messagingSenderId: '216593913852',
    projectId: 'nearby-menus-be6e3',
    databaseURL: 'https://nearby-menus-be6e3.firebaseio.com',
    storageBucket: 'nearby-menus-be6e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOw2JXy1IAeEDde-azU95GfBK6V2EPrjs',
    appId: '1:216593913852:ios:f5b3af87077766cb2f8479',
    messagingSenderId: '216593913852',
    projectId: 'nearby-menus-be6e3',
    databaseURL: 'https://nearby-menus-be6e3.firebaseio.com',
    storageBucket: 'nearby-menus-be6e3.appspot.com',
    androidClientId: '216593913852-o0pvg9kmmh9vn4bnv0fld52p9dohicr9.apps.googleusercontent.com',
    iosClientId: '216593913852-qai1sdmjei24mcgc35fv7p8f41m5vee3.apps.googleusercontent.com',
    iosBundleId: 'com.ernestosoft.nmwhitelabel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOw2JXy1IAeEDde-azU95GfBK6V2EPrjs',
    appId: '1:216593913852:ios:f5b3af87077766cb2f8479',
    messagingSenderId: '216593913852',
    projectId: 'nearby-menus-be6e3',
    databaseURL: 'https://nearby-menus-be6e3.firebaseio.com',
    storageBucket: 'nearby-menus-be6e3.appspot.com',
    androidClientId: '216593913852-o0pvg9kmmh9vn4bnv0fld52p9dohicr9.apps.googleusercontent.com',
    iosClientId: '216593913852-qai1sdmjei24mcgc35fv7p8f41m5vee3.apps.googleusercontent.com',
    iosBundleId: 'com.ernestosoft.nmwhitelabel',
  );
}
