import 'package:flutter/material.dart';

class GreenTheme {
  static final ThemeData theme = ThemeData(
    primarySwatch: Colors.lightGreen,
    brightness: Brightness.light,
    primaryColor: Color(0xff8bc34a),
    primaryColorBrightness: Brightness.light,
    primaryColorLight: Color(0xffdcedc8),
    primaryColorDark: Color(0xff689f38),
    //accentColor: Color(0xff8bc34a),
    //accentColorBrightness: Brightness.light,
    canvasColor: Color(0xfffafafa),
    scaffoldBackgroundColor: Color(0xfffafafa),
    bottomAppBarColor: Color(0xffffffff),
    cardColor: Color(0xffffffff),
    dividerColor: Color(0x1f000000),
    highlightColor: Color(0x66bcbcbc),
    splashColor: Color(0x66c8c8c8),
    selectedRowColor: Color(0xfff5f5f5),
    unselectedWidgetColor: Color(0x8a000000),
    disabledColor: Color(0x61000000),
    //buttonColor: Color(0xffe0e0e0),
    toggleableActiveColor: Color(0xff7cb342),
    secondaryHeaderColor: Color(0xfff1f8e9),
    //textSelectionColor: Color(0xffc5e1a5),
    //cursorColor: Color(0xff4285f4),
    //textSelectionHandleColor: Color(0xffaed581),
    backgroundColor: Color(0xffc5e1a5),
    dialogBackgroundColor: Color(0xffffffff),
    indicatorColor: Color(0xff8bc34a),
    hintColor: Color(0x8a000000),
    errorColor: Color(0xffd32f2f),
    buttonTheme: ButtonThemeData(
      textTheme: ButtonTextTheme.normal,
      minWidth: 88.0,
      height: 36.0,
      padding: EdgeInsets.only(
          top: 0.0, bottom: 0.0, left: 16.0, right: 16.0),
      shape: RoundedRectangleBorder(
        side: BorderSide(
          color: Color(0xff000000), width: 0.0, style: BorderStyle.none,),
        borderRadius: BorderRadius.all(Radius.circular(2.0)),
      )
      ,
      alignedDropdown: false,
      buttonColor: Color(0xffe0e0e0),
      disabledColor: Color(0x61000000),
      highlightColor: Color(0x29000000),
      splashColor: Color(0x1f000000),
      colorScheme: ColorScheme(
        primary: Color(0xff8bc34a),
        primaryVariant: Color(0xff689f38),
        secondary: Color(0xff8bc34a),
        secondaryVariant: Color(0xff689f38),
        surface: Color(0xffffffff),
        background: Color(0xffc5e1a5),
        error: Color(0xffd32f2f),
        onPrimary: Color(0xff000000),
        onSecondary: Color(0xff000000),
        onSurface: Color(0xff000000),
        onBackground: Color(0xff000000),
        onError: Color(0xffffffff),
        brightness: Brightness.light,
      ),
    ),
    textTheme: TextTheme(
      headline1: TextStyle(
        color: Color(0x8a000000),
        fontSize: 96.0,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      headline2: TextStyle(
        color: Color(0x8a000000),
        fontSize: 60.0,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      headline3: TextStyle(
        color: Color(0x8a000000),
        fontSize: 48.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      headline4: TextStyle(
        color: Color(0x8a000000),
        fontSize: 34.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      headline5: TextStyle(
        color: Color(0xdd000000),
        fontSize: 24.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      headline6: TextStyle(
        color: Color(0xdd000000),
        fontSize: 20.0,
        fontWeight: FontWeight.w500,
        fontStyle: FontStyle.normal,
      ),
      subtitle1: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      bodyText1: TextStyle(
        color: Color(0xdd000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      bodyText2: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      caption: TextStyle(
        color: Color(0x8a000000),
        fontSize: 12.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      button: TextStyle(
        color: Color(0xdd000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w500,
        fontStyle: FontStyle.normal,
      ),
      subtitle2: TextStyle(
        color: Color(0xff000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w500,
        fontStyle: FontStyle.normal,
      ),
      overline: TextStyle(
        color: Color(0xff000000),
        fontSize: 10.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    primaryTextTheme: TextTheme(
      headline1: TextStyle(
        color: Color(0x8a000000),
        fontSize: 96.0,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      headline2: TextStyle(
        color: Color(0x8a000000),
        fontSize: 60.0,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      headline3: TextStyle(
        color: Color(0x8a000000),
        fontSize: 48.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      headline4: TextStyle(
        color: Color(0x8a000000),
        fontSize: 34.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      headline5: TextStyle(
        color: Color(0xdd000000),
        fontSize: 24.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      headline6: TextStyle(
        color: Color(0xdd000000),
        fontSize: 20.0,
        fontWeight: FontWeight.w500,
        fontStyle: FontStyle.normal,
      ),
      subtitle1: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      bodyText1: TextStyle(
        color: Color(0xdd000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      bodyText2: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      caption: TextStyle(
        color: Color(0x8a000000),
        fontSize: 12.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      button: TextStyle(
        color: Color(0xdd000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w500,
        fontStyle: FontStyle.normal,
      ),
      subtitle2: TextStyle(
        color: Color(0xff000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w500,
        fontStyle: FontStyle.normal,
      ),
      overline: TextStyle(
        color: Color(0xff000000),
        fontSize: 10.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    // accentTextTheme: TextTheme(
    //   headline1: TextStyle(
    //     color: Color(0x8a000000),
    //     fontSize: 96.0,
    //     fontWeight: FontWeight.w300,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   headline2: TextStyle(
    //     color: Color(0x8a000000),
    //     fontSize: 60.0,
    //     fontWeight: FontWeight.w300,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   headline3: TextStyle(
    //     color: Color(0x8a000000),
    //     fontSize: 48.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   headline4: TextStyle(
    //     color: Color(0x8a000000),
    //     fontSize: 34.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   headline5: TextStyle(
    //     color: Color(0xdd000000),
    //     fontSize: 24.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   headline6: TextStyle(
    //     color: Color(0xdd000000),
    //     fontSize: 20.0,
    //     fontWeight: FontWeight.w500,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   subtitle1: TextStyle(
    //     color: Color(0xdd000000),
    //     fontSize: 16.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   bodyText1: TextStyle(
    //     color: Color(0xdd000000),
    //     fontSize: 14.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   bodyText2: TextStyle(
    //     color: Color(0xdd000000),
    //     fontSize: 16.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   caption: TextStyle(
    //     color: Color(0x8a000000),
    //     fontSize: 12.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   button: TextStyle(
    //     color: Color(0xdd000000),
    //     fontSize: 14.0,
    //     fontWeight: FontWeight.w500,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   subtitle2: TextStyle(
    //     color: Color(0xff000000),
    //     fontSize: 14.0,
    //     fontWeight: FontWeight.w500,
    //     fontStyle: FontStyle.normal,
    //   ),
    //   overline: TextStyle(
    //     color: Color(0xff000000),
    //     fontSize: 10.0,
    //     fontWeight: FontWeight.w400,
    //     fontStyle: FontStyle.normal,
    //   ),
    // ),
    inputDecorationTheme: InputDecorationTheme(
      labelStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      helperStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      hintStyle: TextStyle(
        color: Color(0xffff9800),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      errorStyle: TextStyle(
        color: Color(0xffd32f2f),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      errorMaxLines: null,
      floatingLabelBehavior: FloatingLabelBehavior.never,
      isDense: false,
      contentPadding: EdgeInsets.only(
          top: 12.0, bottom: 12.0, left: 0.0, right: 0.0),
      isCollapsed: false,
      prefixStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      suffixStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      counterStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: 16.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      filled: false,
      fillColor: Color(0x00000000),
      errorBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000), width: 1.0, style: BorderStyle.solid,),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      focusedBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000), width: 1.0, style: BorderStyle.solid,),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      focusedErrorBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000), width: 1.0, style: BorderStyle.solid,),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      disabledBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000), width: 1.0, style: BorderStyle.solid,),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      enabledBorder: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000), width: 1.0, style: BorderStyle.solid,),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      border: UnderlineInputBorder(
        borderSide: BorderSide(
          color: Color(0xff000000), width: 1.0, style: BorderStyle.solid,),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
    ),
    iconTheme: IconThemeData(
      color: Color(0xdd000000),
      opacity: 1.0,
      size: 24.0,
    ),
    primaryIconTheme: IconThemeData(
      color: Color(0xff000000),
      opacity: 1.0,
      size: 24.0,
    ),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      foregroundColor: Color(0xff000000),
    ),
    // accentIconTheme: IconThemeData(
    //   color: Color(0xff000000),
    //   opacity: 1.0,
    //   size: 24.0,
    // ),
    sliderTheme: SliderThemeData(
      activeTrackColor: Color(0xff8bc34a),
      inactiveTrackColor: Color(0x3d8bc34a),
      disabledActiveTrackColor: Color(0x52689f38),
      disabledInactiveTrackColor: Color(0x1f689f38),
      activeTickMarkColor: Color(0x8adcedc8),
      inactiveTickMarkColor: Color(0x8a8bc34a),
      disabledActiveTickMarkColor: Color(0x1fdcedc8),
      disabledInactiveTickMarkColor: Color(0x1f689f38),
      thumbColor: Color(0xff8bc34a),
      disabledThumbColor: Color(0x52689f38),
      thumbShape: RoundSliderThumbShape(),
      overlayColor: Color(0x298bc34a),
      valueIndicatorColor: Color(0xff8bc34a),
      valueIndicatorShape: PaddleSliderValueIndicatorShape(),
      showValueIndicator: ShowValueIndicator.onlyForDiscrete,
      valueIndicatorTextStyle: TextStyle(
        color: Color(0xdd000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
    ),
    tabBarTheme: TabBarTheme(
      indicatorSize: TabBarIndicatorSize.tab,
      labelColor: Color(0xdd000000),
      unselectedLabelColor: Color(0xb2000000),
    ),
    chipTheme: ChipThemeData(
      backgroundColor: Color(0x1f000000),
      brightness: Brightness.light,
      deleteIconColor: Color(0xde000000),
      disabledColor: Color(0x0c000000),
      labelPadding: EdgeInsets.only(
          top: 0.0, bottom: 0.0, left: 8.0, right: 8.0),
      labelStyle: TextStyle(
        color: Color(0xde000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      padding: EdgeInsets.only(top: 4.0, bottom: 4.0, left: 4.0, right: 4.0),
      secondaryLabelStyle: TextStyle(
        color: Color(0x3d000000),
        fontSize: 14.0,
        fontWeight: FontWeight.w400,
        fontStyle: FontStyle.normal,
      ),
      secondarySelectedColor: Color(0x3d8bc34a),
      selectedColor: Color(0x3d000000),
      shape: StadiumBorder(side: BorderSide(
        color: Color(0xff000000), width: 0.0, style: BorderStyle.none,)),
    ),
    dialogTheme: DialogTheme(
        shape: RoundedRectangleBorder(
          side: BorderSide(color: Color(0xff000000),
            width: 0.0,
            style: BorderStyle.none,),
          borderRadius: BorderRadius.all(Radius.circular(0.0)),
        )

    ),
  );
}
